# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa0ef0f75484973c831df66091dc3060543a97e335e28101b2e3143d3c79edbd18fca713bdcb083abd391af0020f3c063e3ec0149840cb10976da355e2cc9332

test:
  secret_key_base: b90e7b02d3873ea2f87c6c64c0d370e86b2a4adeffd018e1d25de031657666b12178991a1bc033209d304f9a6bb967ed1e52321daf94cba059fe1231536b0bd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
